/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_daemon_nativecallback_MSDKNativeCallBack */

#ifndef _Included_com_daemon_nativecallback_MSDKNativeCallBack
#define _Included_com_daemon_nativecallback_MSDKNativeCallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_daemon_nativecallback_MSDKNativeCallBack
 * Method:    changeToWelcomeScene
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_daemon_nativecallback_MSDKNativeCallBack_changeToWelcomeScene
  (JNIEnv *, jclass);

/*
 * Class:     com_daemon_nativecallback_MSDKNativeCallBack
 * Method:    changeToLoginScene
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_daemon_nativecallback_MSDKNativeCallBack_changeToLoginScene
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
