/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_daemon_nativecallback_MSDKCallBack */
#include "LoginScene.h"
#include "WelcomeScene.h"
#include "GameScene.h"
#include "platform/android/jni/JniHelper.h"

#ifndef _Included_com_daemon_nativecallback_MSDKNativeCallBack
#define _Included_com_daemon_nativecallback_MSDKNativeCallBack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_daemon_nativecallback_MSDKCallBack
 * Method:    changeToWelcomeScene
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_daemon_nativecallback_MSDKNativeCallBack_changeToWelcomeScene
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
